# Generated by Django 5.0.1 on 2024-02-16 19:44

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to=users.models.PathAndRename('profile_pics')),
        ),
    ]
