# Generated by Django 5.0.1 on 2024-02-16 19:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='content',
            field=models.ImageField(upload_to=blog.models.PathAndRename('profile_pics')),
        ),
    ]
