# Generated by Django 5.0.1 on 2024-02-18 10:10

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='content',
            field=models.FileField(null=True, upload_to=blog.models.PathAndRename('profile_pics'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
